/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.1-2-gcc33e73618-20211214"
#endif /* AVUTIL_FFVERSION_H */
